# Simple deployment used to deploy and manage the app in nigelpoulton/ps-web:1.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kube-web-deploy
  labels:
    app: hello-kube-dep
spec:
  selector:
    matchLabels:
      app: hello-kube-web
  replicas: 3
  minReadySeconds: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-kube-web
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: hello-kube-ctr
        image: registry.hub.docker.com/esakkimuthua12/test:mytest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080