apiVersion: v1
kind: Service
metadata:
  name: hello-kube-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30036
      protocol: TCP
  selector:
    name: hello-kube-web
    